### PR TITLE
Enable prettier-java for formatting

### PR DESCRIPTION
**Pull request by jhaber**
@mattcoley @boulter @hs-lsong

### CODE REVIEW

**Comment by jhaber** [comment]
Getting a findbugs error, probably because the basepom upgrade picked up a new version of findbugs

**Comment by mattcoley** [comment]
Do we have a guide for non-hubspot devs contributing to this repo if prettier is enabled?

**Comment by jhaber** [comment]
Code should automatically get reformatted on build so they shouldn't need to do anything special besides building before committing. To just reformat without running a full build you can do `mvn prettier:write`

**Comment by mattcoley** [comment]
👍 We can add that to the readme.

**Comment by jhaber** [comment]
Suppressed the findbugs warning, it might actually be due to a Guava upgrade rather than a findbugs change (seems like they now use a `@NullableDecl` annotation which findbugs isn't treating as nullable)

**Comment by jhaber** [comment]
It's probably lost in the massive diff, but I also slimmed down the checkstyle configuration to remove things that are superseded by prettier

**Pull request merged**
