### PR TITLE
Interpreter rework

### PR DESCRIPTION
**Pull request by markus-s24**
Replaced VariableChain by using the SimpleResolver.

### CODE REVIEW

**Comment by markus-s24** [comment]
I am finished with my changes now :-) What do you think about them?

**Comment by jaredstehler** [comment]
still checking them out.. so far things look good!

**Comment by jaredstehler** [comment]
so is ```JinjavaPropertyNotResolvedException``` no longer needed, in that everything will be thrown in a ```PropertyNotFoundException```?

**Comment by jaredstehler** [comment]
the liquid benchmark is failing, it seems that map property names aren't resolving with this:

```collections.frontpage.products```

```
java.lang.IllegalArgumentException: Cannot parse list index: frontpage
	at javax.el.ListELResolver.toIndex(ListELResolver.java:307)
	at javax.el.ListELResolver.getValue(ListELResolver.java:159)
	at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:231)
	at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:231)
	at de.odysseus.el.util.SimpleResolver.getValue(SimpleResolver.java:120)
	at com.hubspot.jinjava.el.JinjavaInterpreterResolver.getValue(JinjavaInterpreterResolver.java:107)
	at com.hubspot.jinjava.el.JinjavaInterpreterResolver.getValue(JinjavaInterpreterResolver.java:87)
```

**Comment by jaredstehler** [comment]
which is odd, because ```itResolvesDictValWithDotParam``` is passing. I'll dig in further...

**Comment by jaredstehler** [comment]
nvm, that was an issue in the liquid benchmark already :(

**Comment by jaredstehler** [comment]
thanks!

**Comment by markus-s24** [comment]
All cases now throw a PropertyNotFoundException, because the custom reflection code (which was the only source of JinjavaPropertyNotResolvedExceptions) has been removed.

Thanks for accepting the patch and sorry for the late answer.

**Pull request merged**
