### PR TITLE
Revert "Revert "Filter upgrades to support kw params""

### PR DESCRIPTION
**Pull request by boulter**
Reverts HubSpot/jinjava#533

@michaelpro1 can you take a look?

### CODE REVIEW

**Comment by mattcoley** [comment]
To follow up, I think we should be using the TruthyTypeConverter instead of straight up casting of objects to mimic Python behavior.

**Comment by michaelpro1** [comment]
Hi @boulter @mattcoley is there a jinja template with expected output that could help verify this?

**Comment by michaelpro1** [comment]
Please take a look at [my branch](https://github.com/michaelpro1/jinjava/tree/revert-533-revert-531-feature/abstractfilter-upgrades-1) that uses TruthyTypeConverter.
Diff: https://github.com/HubSpot/jinjava/compare/revert-533-revert-531-feature/abstractfilter-upgrades-1...michaelpro1:revert-533-revert-531-feature/abstractfilter-upgrades-1

**Comment by boulter** [comment]
@michaelpro1 I merged in your changes.

**Pull request merged**
