### PR TITLE
Change initialization of JinjavaInterpreter to instantiation

### PR DESCRIPTION
**Pull request by Roobun**
Now it's possible to override instantiate method
It'll be helpful if you use extended interpreter

### CODE REVIEW

**Comment by mattcoley** [comment]
I believe you will also have to look at https://github.com/HubSpot/jinjava/blob/master/src/main/java/com/hubspot/jinjava/Jinjava.java which also creates interpreters.

**Comment by mattcoley** [comment]
Maybe we can use a factory pattern for the `JinjavaInterpreter` and set the factory on the `JinjavaConfig`. So there would be some interface `InterpreterFactory` with a default `JinjavaInterpreterFactory` that is set as a field on `JinjavaConfig`. Everywhere we create a new interpreter would instead use `config.getInterpreterFactory().newInstance(...)`. You could then create your own factory to serve your own interpreters and set that value in the config.

**Comment by Roobun** [comment]
> Maybe we can use a factory pattern for the `JinjavaInterpreter` and set the factory on the `JinjavaConfig`. So there would be some interface `InterpreterFactory` with a default `JinjavaInterpreterFactory` that is set as a field on `JinjavaConfig`. Everywhere we create a new interpreter would instead use `config.getInterpreterFactory().newInstance(...)`. You could then create your own factory to serve your own interpreters and set that value in the config.

Sure. Please take a look at new changes I added.

**Comment by mattcoley** [comment]
I'll merge and do a release

**Pull request merged**
