### PR TITLE
Build and run with Java 7

### PR DESCRIPTION
**Pull request by skitt**
I understand if you'd rather reject this of course! I needed support for Java 7 so I adapted the code, there aren't many changes. I used threeten to provide the JSR-310 date/time support.

### CODE REVIEW

**Comment by skitt** [comment]
So it builds and runs on JDK 7, but a build on JDK 7 or 8 fails when run on JDK 8...

**Comment by skitt** [comment]
The failure is due to a change in date formatting between JDK 7 and 8 (see http://hg.openjdk.java.net/jdk7/jdk7/jdk/file/9b8c96f96a0f/src/share/classes/sun/text/resources/FormatData_fi.java and http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/classes/sun/text/resources/fi/FormatData_fi.java for details).

**Comment by jaredstehler** [comment]
I believe that this is the main reason we needed to move to java 8; we encountered this Finnish date formatting bug!

**Comment by skitt** [comment]
After digging around, it turns out this is a JDK bug: https://bugs.openjdk.java.net/browse/JDK-8074791 (fixed in OpenJDK 9...).

**Comment by jaredstehler** [comment]
I wonder if we could do this with a separate maven build profile, publishing a ```java7``` classified artifact?

**Comment by Mogztter** [comment]
> I wonder if we could do this with a separate maven build profile, publishing a java7 classified artifact?

Why not but we still need to modify some code. Do you prefer to create a separate branch or to replace/modify the code before the build ?

**Comment by jaredstehler** [comment]
I'm leaning towards the separate branch approach; I'll play around with this and see if I can't publish it to sonatype with the java7 classifier

**Comment by jaredstehler** [comment]
looks like there may be some issues where java8 is better at generic detection than java7:

```
[ERROR] /Users/jstehler/dev/src/java/jinjava/src/main/java/com/hubspot/jinjava/doc/JinjavaDocFactory.java:[50,24] constructor JinjavaDocExpTest in class com.hubspot.jinjava.doc.JinjavaDocExpTest cannot be applied to given types;
[ERROR] required: java.lang.String,java.lang.String,java.lang.String,boolean,com.hubspot.jinjava.doc.JinjavaDocParam[],com.hubspot.jinjava.doc.JinjavaDocSnippet[],java.util.Map<java.lang.String,java.lang.String>
[ERROR] found: java.lang.String,java.lang.String,java.lang.String,boolean,com.hubspot.jinjava.doc.JinjavaDocParam[],com.hubspot.jinjava.doc.JinjavaDocSnippet[],java.util.Map<java.lang.Object,java.lang.Object>
[ERROR] reason: actual argument java.util.Map<java.lang.Object,java.lang.Object> cannot be converted to java.util.Map<java.lang.String,java.lang.String> by method invocation conversion
[ERROR] /Users/jstehler/dev/src/java/jinjava/src/main/java/com/hubspot/jinjava/doc/JinjavaDocFactory.java:[65,23] constructor JinjavaDocFilter in class com.hubspot.jinjava.doc.JinjavaDocFilter cannot be applied to given types;
[ERROR] required: java.lang.String,java.lang.String,java.lang.String,boolean,com.hubspot.jinjava.doc.JinjavaDocParam[],com.hubspot.jinjava.doc.JinjavaDocSnippet[],java.util.Map<java.lang.String,java.lang.String>
[ERROR] found: java.lang.String,java.lang.String,java.lang.String,boolean,com.hubspot.jinjava.doc.JinjavaDocParam[],com.hubspot.jinjava.doc.JinjavaDocSnippet[],java.util.Map<java.lang.Object,java.lang.Object>
[ERROR] reason: actual argument java.util.Map<java.lang.Object,java.lang.Object> cannot be converted to java.util.Map<java.lang.String,java.lang.String> by method invocation conversion
[ERROR] /Users/jstehler/dev/src/java/jinjava/src/main/java/com/hubspot/jinjava/doc/JinjavaDocFactory.java:[90,27] constructor JinjavaDocFunction in class com.hubspot.jinjava.doc.JinjavaDocFunction cannot be applied to given types;
[ERROR] required: java.lang.String,java.lang.String,java.lang.String,boolean,com.hubspot.jinjava.doc.JinjavaDocParam[],com.hubspot.jinjava.doc.JinjavaDocSnippet[],java.util.Map<java.lang.String,java.lang.String>
[ERROR] found: java.lang.String,java.lang.String,java.lang.String,boolean,com.hubspot.jinjava.doc.JinjavaDocParam[],com.hubspot.jinjava.doc.JinjavaDocSnippet[],java.util.Map<java.lang.Object,java.lang.Object>
[ERROR] reason: actual argument java.util.Map<java.lang.Object,java.lang.Object> cannot be converted to java.util.Map<java.lang.String,java.lang.String> by method invocation conversion
[ERROR] /Users/jstehler/dev/src/java/jinjava/src/main/java/com/hubspot/jinjava/doc/JinjavaDocFactory.java:[109,20] constructor JinjavaDocTag in class com.hubspot.jinjava.doc.JinjavaDocTag cannot be applied to given types;
[ERROR] required: java.lang.String,boolean,java.lang.String,java.lang.String,boolean,com.hubspot.jinjava.doc.JinjavaDocParam[],com.hubspot.jinjava.doc.JinjavaDocSnippet[],java.util.Map<java.lang.String,java.lang.String>
[ERROR] found: java.lang.String,boolean,java.lang.String,java.lang.String,boolean,com.hubspot.jinjava.doc.JinjavaDocParam[],com.hubspot.jinjava.doc.JinjavaDocSnippet[],java.util.Map<java.lang.Object,java.lang.Object>
[ERROR] reason: actual argument java.util.Map<java.lang.Object,java.lang.Object> cannot be converted to java.util.Map<java.lang.String,java.lang.String> by method invocation conversion
```

I've merged your branch with current master here if you want to check it out: https://github.com/HubSpot/jinjava/tree/skitt-java7

**Comment by jaredstehler** [comment]
I've deployed this branch to sonatype as:
```
<dependency>
  <groupId>com.hubspot.jinjava</groupId>
  <artifactId>jinjava</artifactId>
  <version>2.0.11-java7</version>
</dependency>
```

It should sync within 6 hours or so.

**Comment by Mogztter** [comment]
Cool thanks @jajoneill !

**Pull request closed without merging**
