### PR TITLE
Return long value from int filter if over max int length.

### PR DESCRIPTION
**Pull request by mattcoley**
Int is unbounded in python so trying to come up with a solution to bring Jinjava `|int` closer to parity with Jinja. Here we are returning a long value instead of a int if the value is above the maximum allowed for ints. This should fix most issues where people are trying to convert long IDs into numbers using the `|int` filter. Some thought is needed to figure out a better long term solution for higher values than what long supports.

### CODE REVIEW

**Comment by boulter** [comment]
would there be harm in always returning a `long` from the `int` filter if in python `|int` means any whole number?

**Comment by mattcoley** [comment]
Not sure what the implications are for always returning `long` so I am trying to be safe by only returning long if the value overflows.

**Comment by mattcoley** [comment]
Filters/functions that don't do type conversions (i.e. advanced filters) may be affected by always returning a long.

**Comment by boulter** [comment]
> Filters/functions that don't do type conversions (i.e. advanced filters) may be affected by always returning a long.

I'd say it would be more likely to create problems if the returned type varies by input. Users won't expect they'll sometimes get longs.

**Comment by mattcoley** [comment]
I am going to fix type conversion in a few other places then make this always return long.

**Comment by mattcoley** [comment]
The only issue I can think of is if you explicitly check for the type: `type(num) == 'int'`

**Pull request merged**
