### PR TITLE
Filter upgrades to support kw params

### PR DESCRIPTION
**Pull request by mattcoley**
Reverts HubSpot/jinjava#539

Looking into some diffs around datetimeformat filter

### CODE REVIEW

**Comment by mattcoley** [comment]
The main issue has to do with https://github.com/HubSpot/jinjava/issues/271. I fixed this by manually overriding the `coerceToString` method. This has the added effect of enums not roundtripping however, it adds equality between enums and strings which is more desirable. In Jinjava we lose all type information on conversion so we never coerce back to the enum.

**Review by boulter — APPROVED** [review]

**Comment by michaelpro1** [comment]
out of curiousity whats an example of an enum used?

**Comment by mattcoley** [comment]
There isn't a way to declare an enum or create one via Jinjava, however an often use case is to add an enum value to the context. Previously functions would typically accept generic Object values and call `toString()` to extract the String, however the TruthyTypeConverter extends a type converter from Juel that was calling `name()` which can be different depending on the enum. I am planning on merging this soon and rechecking our diff reports to make sure everything is OK.

**Comment by michaelpro1** [comment]
Noticed that this PR has been sitting for a little while, did you need any help with it?

**Comment by mattcoley** [comment]
Let me merge this in again and check our custom diff reports.

**Pull request merged**
